workflows:
  - name: Self Updater
    file: gha_updater.yml
    triggers:
      push:
        branches:
          - master
        paths:
          - '.github/workflows.yml'
          - '.github/workflows/*.yml'
      schedule:
        - cron:  '1 6-22 * * 1-5'
    jobs:
      - name: update_gha
        template: util/update_gha
        template_args:
          timeout_minutes: 5
