name: Lint and validate

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  shellcheck:
    # Use newer os for more up-to-date shellcheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Run shellcheck on .sh and .bash files files
        run: |
          find . -name '*.sh' -exec shellcheck -s bash '{}' \+
          find . -name '*.bash' -exec shellcheck -s bash '{}' \+

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.1"
      - name: Install kojo
        run: gem install kojo
      - run: make
      - name: Check for changes
        run: |
          git status
          git_changes="$(git status --porcelain || true)"
          # If the output is not empty, there are changes; fail the action
          if [ -n "$git_changes" ]; then
              git diff
              echo "Changes found; build the action with 'make' and commit the changes"
              exit 1
          fi
